### ISSUE TITLE
column titles

### ISSUE THREAD

**Issue by fmof** [kebegaoussou/mlmc#1]
What are the column titles? Is it data and labels?

**Comment by gkebe** [comment]
yes. data and labels are the headers like in the samples.

**Comment by fmof** [comment]
Ah, so the multilabel examples (https://github.com/kebegaoussou/mlmc/blob/master/multilabel_sample/train.tsv) are just showing that you can also have extra columns?

If so, can you please make a note of that in the readme?

**Comment by gkebe** [comment]
Done.

**Comment by fmof** [comment]
Thanks!
